### ISSUE TITLE
Diagramas de casos de uso

### ISSUE THREAD

**Issue by martinsaposnic** [martinsaposnic/tp-dds#1]
Diagrama de casos de uso: deberá ser general, es decir, contener todos los casos de uso que hayan identificado tanto en el contexto general presentado como lo detallado específicamente en esta entrega. Además, se puede presentar especificaciones de requerimientos, tabla de requerimientos
funcionales, diagramas de Secuencia, entre otros.

**Comment by ivanchan194** [comment]
Diagrama subido al drive
