### ISSUE TITLE
Diagrama de arquitectura

### ISSUE THREAD

**Issue by martinsaposnic** [martinsaposnic/tp-dds#2]
deberá ser un diagrama que muestre la arquitectura del sistema a alto nivel. Debe quedar en claro: 
componentes de alto nivel, sistemas externos (si los hubiera) y comunicación entre componentes. No es necesario un gran nivel de detalle.

**Comment by ericcano777** [comment]
Version actualizada del diseño de arquitectura, combinamos cliente-servidor (usuario-server) con modelo mvc.
![diseno de arquitectura v1 1](https://user-images.githubusercontent.com/37750591/38993285-8a329256-43b9-11e8-82b0-7b8a81af58b4.jpeg)
